title: My life and data diary
description: Sharing my thoughts on life and data engineering, while practising my writing skills. 
author: "George Petropoulos"

theme: minima


# Minima social links
github_username: geopet85
linkedin_username: geopetropoulos
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/welcome.md
  - _pages/about.md
  - _pages/cv.md
  - _pages/blog.md

include:
    - _pages
