title: My data and life diary
description: I just practise my writing skills
author: "George Petropoulos"

theme: minima


# Minima social links
github_username: geopet85
linkedin_username: geopetropoulos
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/welcome.md
  - _pages/about.md
  - _pages/blog.md

include:
    - _pages
