theme: minima

header_pages:
  - about.md
  - blog.md
  - random_quotes.md

title: My data and life diary
author:
  name: George Petropoulos
  email: geopet85 at gmail dot com
description: > 
  I am here just to practise my writing skills 
  and share a couple stories from software engineering and life.
show_excerpts: true 

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: geopet85
    github:  geopet85
